# Over2Craft Freebuild Core by DubSlime
# Available placeholders :
# %PLAYER% => The player who mentioned
# %TARGET% => The player who has been mentioned

symbol: "@" # Define the symbol needed to create a mention
color: "&6" # Define the color that highlights the mention

# SOUND EFFECTS
toggleSound: true # Play a sound to the player when he is mentioned
soundName: "ENTITY_PLAYER_LEVELUP" # Name of the sound that should be played 
soundVolume: 1 # Volume of the sound
soundPitch: 0 # Pitch of the sound (0 = default)

# MESSAGES
toggleMessage: true # Send a message to the player when he is mentioned
toggleActionBar: true # Use the action bar to display messages
chatMessage: "&6%PLAYER% &3vous a mentionné !"
actionBarMessage: ">> &6%PLAYER% vous a mentionné ! <<"
reloadMessage: "&3[&6O&32&2C &3Freecore] Fichier de configuration rechargé !"